[package]
name = "meteostat-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json", "gzip", "stream"] }
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0", features = ["unbounded_depth"] }
flate2 = "1.1.1"
geo = "0.30"
polars = { version = "0.46.0", features = ["csv", "dtype-datetime", "temporal", "strings"] }
thiserror = "2.0.12"
chrono = "0.4"
log = "0.4"
env_logger = "0.11"
geographiclib-rs = "0.2"
tokio = { version = "1.44.2", features = ["full"] }
anyhow = "1.0.97"
futures-util = "0.3.31"
tokio-util = { version = "0.7.14", features = ["io-util"] }
tempfile = "3.19.1"
bytes = "1.10.1"