name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      # Install and cache system dependencies
      - name: Cache and install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libfontconfig1-dev pkg-config
          version: 1.0

      - name: Check formatting
        run: cargo fmt --all -- --check

      # Build
      - name: Build
        run: cargo build --all-targets --all-features

      # Run Clippy
      - name: Run Clippy
        run: |
          cargo clippy --all-features -- \
          -D warnings -W clippy::pedantic \
          -W clippy::nursery

      # Run tests
      - name: Run tests
        run: cargo test -- --test-threads 1

      # Documentation check
      - name: Check documentation
        run: cargo doc --no-deps --document-private-items