name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Rust setup
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libfontconfig1-dev pkg-config

      # Format check
      - name: Check formatting
        run: cargo fmt --all -- --check

      # Strict Clippy checks
      - name: Run Clippy (strict)
        run: |
          cargo clippy --all-targets --all-features -- -D warnings -A clippy::missing_errors_doc -A clippy::missing_panics_doc

      # Run tests
      - name: Run tests
        run: cargo test -- --test-threads 1

      # Documentation check
      - name: Check documentation
        run: cargo doc --no-deps --document-private-items